trigger: none
jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'Ubuntu-latest'
  environment:
    name: nodeCI
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - script: npm install
                    npm start