jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'Ubuntu-latest'
  environment:
    name: web
    resourceType: VirtualMachine
  strategy:
      runOnce:
        deploy:
          steps:
          - script: git clone https://github.com/syedimranFB/ExpressJS.git ; cd ExpressJS ; npm install ; cp hello.js /var/www/html