trigger: none

pool:
  vmImage: windows-latest

stages:

- stage: Build
  dependsOn: [] # This will remove implicit dependency and run in parallel with the stage: Tests above 
  jobs:
  - job:
    displayName: Build the application
    steps:
    - script: |
        npm install
        npm run
        npm exec
        echo ... commands successfully completed.
      displayName: 'Run build scripts & tasks'

- stage: Dev
  dependsOn:
  - Build
  jobs:
  - deployment:
    displayName: Dev deploy
    environment: local
    strategy:
     runOnce:
       deploy:
         steps:
           - script: npm install
                     npm start
             displayName: 'Dev based stage'